spring:
  datasource:
    url: jdbc:h2:mem:credit_application-system_db
    username: vini
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false